a = int(input('Intoduzca el valor a: '))
b = int(input('Intoduzca el valor b: '))
print("Su suma es:", a + b)
print("Su resta es:", a - b)
print("Su multiplicación es:", a * b)
print("Su división es:", a / b)