/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletests;

public class GestorArrays {
    private int[] arrayInts;

    public GestorArrays(int[] arrayInts) {
        this.arrayInts = arrayInts;
    }

    public int contarElementos() {
        return arrayInts.length;
    }

    public int devolverPrimero() {
        if (arrayInts.length > 0) {
            return arrayInts[0];
        } else {
            throw new IllegalStateException("El array está vacío");
        }
    }

    public int devolverUltimo() {
        if (arrayInts.length > 0) {
            return arrayInts[arrayInts.length - 1];
        } else {
            throw new IllegalStateException("El array está vacío");
        }
    }

    public int devolverTercero() {
        if (arrayInts.length >= 3) {
            return arrayInts[2];
        } else {
            throw new IllegalStateException("El array no tiene al menos tres elementos");
        }
    }

    public int sumaElementos() {
        int suma = 0;
        for (int num : arrayInts) {
            suma += num;
        }
        return suma;
    }

    public double mediaElementos() {
        if (arrayInts.length == 0) {
            throw new IllegalStateException("El array está vacío");
        }
        return (double) sumaElementos() / arrayInts.length;
    }
}
